# Generated by Django 3.2.5 on 2022-03-27 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Model Category Field name')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='product.category', verbose_name='Model Category Field parent')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Model Product Field title')),
                ('description', models.CharField(max_length=100, verbose_name='Model Product Field description')),
                ('url', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Model Product Field url')),
                ('create_date', models.DateTimeField(blank=True, editable=False, verbose_name='Model Field create_date')),
                ('update_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Model Field update_date')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='Model Product Field category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Model Product Field user')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Model ProductVariant Field name')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Model ProductVariant Field description')),
                ('price', models.FloatField(blank=True, verbose_name='Model ProductVariant Field price')),
                ('current', models.BooleanField(default=True, verbose_name='Model ProductVariant Field current')),
                ('approved', models.BooleanField(blank=True, default=None, null=True, verbose_name='Model ProductVariant Field approved')),
                ('create_date', models.DateTimeField(blank=True, editable=False, verbose_name='Model Field create_date')),
                ('update_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Model Field update_date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product', verbose_name='Model ProductImage Field product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images', verbose_name='Model ProductImage Field image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='Model ProductImage Field product')),
            ],
        ),
    ]
