# Generated by Django 3.2.5 on 2022-03-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approved',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Model Product Field approved'),
        ),
    ]
