# Generated by Django 3.2.5 on 2022-03-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='approved',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Model ProductImage Field approved'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='delete',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Model ProductImage Field delete'),
        ),
    ]
