# Generated by Django 3.2.5 on 2022-04-09 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20220327_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Model Feature Field name')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Model FeatureValue Field name')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='product.feature', verbose_name='Model FeatureValue Field feature')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Model FeatureOption Field name')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='product.feature', verbose_name='Model FeatureOption Field feature')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='features',
            field=models.ManyToManyField(to='product.Feature', verbose_name='Model Category Field features'),
        ),
        migrations.AddField(
            model_name='product',
            name='feature_options',
            field=models.ManyToManyField(to='product.FeatureOption', verbose_name='Model Product Field feature_options'),
        ),
        migrations.AddField(
            model_name='product',
            name='feature_values',
            field=models.ManyToManyField(to='product.FeatureValue', verbose_name='Model Product Field feature_values'),
        ),
    ]
