# Generated by Django 3.2.5 on 2022-04-09 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20220409_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='feature_values',
        ),
        migrations.AddField(
            model_name='featurevalue',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feature_values', to='product.product', verbose_name='Model FeatureValue Field product'),
            preserve_default=False,
        ),
    ]
