# Generated by Django 3.2.5 on 2022-04-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20220409_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='inventory',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Model ProductVariant Field inventory'),
        ),
    ]
