# Generated by Django 3.2.5 on 2022-04-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productvariant_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdraft',
            name='feature_options',
            field=models.ManyToManyField(to='product.FeatureOption', verbose_name='Model ProductDraft Field feature_options'),
        ),
    ]
