# Generated by Django 3.2.5 on 2022-04-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productdraft_feature_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='disable_parent_features',
            field=models.BooleanField(default=False, verbose_name='Model Category Field disable_parent_features'),
        ),
    ]
