# Generated by Django 3.2.5 on 2022-04-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_category_disable_parent_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='features',
            field=models.ManyToManyField(blank=True, to='product.Feature', verbose_name='Model Category Field features'),
        ),
    ]
