# Generated by Django 3.2.5 on 2023-07-18 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_category_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='price',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='feature_options',
            field=models.ManyToManyField(to='product.FeatureOption', verbose_name='Model ProductVariant Field feature_options'),
        ),
        migrations.CreateModel(
            name='ProductVariantDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Model ProductDraft Field title')),
                ('description', models.CharField(max_length=100, verbose_name='Model ProductDraft Field description')),
                ('feature_options', models.ManyToManyField(to='product.FeatureOption', verbose_name='Model ProductDraft Field feature_options')),
                ('original', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='product.productvariant', verbose_name='Model ProductVariantDraft Field original')),
            ],
        ),
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, verbose_name='Model ProductListing Field price')),
                ('is_obsolete', models.BooleanField(blank=True, default=False, verbose_name='Model ProductListing Field is_obsolete')),
                ('create_date', models.DateTimeField(blank=True, editable=False, verbose_name='Model ProductListing create_date')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='product.product', verbose_name='Model ProductListing Field product_variant')),
            ],
        ),
    ]
