# Generated by Django 3.2.5 on 2022-03-27 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[], max_length=2, verbose_name='Model Notification Field type')),
                ('message', models.CharField(max_length=200, verbose_name='Model Notification Field message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Model Notification Field is_read')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Model Notification Field created_at')),
                ('notified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_made', to=settings.AUTH_USER_MODEL, verbose_name='Model Notification Field notified_by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Model Notification Field user')),
            ],
        ),
    ]
