# Generated by Django 3.2.5 on 2022-03-27 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, verbose_name='Model LoginToken Field token')),
                ('create_date', models.DateTimeField(blank=True, editable=False, verbose_name='Model LoginToken Field create_date')),
                ('expire_date', models.DateTimeField(blank=True, editable=False, verbose_name='Model LoginToken Field expire_date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL, verbose_name='Model LoginToken Field user')),
            ],
        ),
    ]
