# Generated by Django 3.2.5 on 2023-07-18 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20230718_0303'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, verbose_name='Model Fulfillment Field tracking_number')),
                ('tracking_link', models.CharField(max_length=100, verbose_name='Model Fulfillment Field tracking_link')),
                ('is_obsolete', models.BooleanField(blank=True, default=False, verbose_name='Model Fulfillment Field is_obsolete')),
                ('created_at', models.DateTimeField(blank=True, verbose_name='Model Fulfillment Field create_date')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Model Fulfillment Field update_date')),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Model LineItem Field count')),
                ('created_at', models.DateTimeField(blank=True, verbose_name='Model LineItem Field create_date')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Model LineItem Field update_date')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shipped', models.BooleanField(blank=True, default=False, verbose_name='Model Package Field is_shipped')),
                ('is_obsolete', models.BooleanField(blank=True, default=False, verbose_name='Model Package Field is_obsolete')),
                ('desi', models.FloatField(blank=True, null=True, verbose_name='Model Package Field desi')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Model Package Field weight')),
                ('created_at', models.DateTimeField(blank=True, verbose_name='Model Package Field create_date')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Model Package Field update_date')),
                ('lines', models.ManyToManyField(related_name='packages', to='order.LineItem', verbose_name='Model Package Field order')),
            ],
        ),
        migrations.CreateModel(
            name='PackageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(blank=True, verbose_name='Model Package Field created_at')),
                ('status', models.CharField(choices=[('0', 'Created'), ('1', 'Preparing'), ('2', 'Packaged'), ('3', 'In Cargo'), ('4', 'In Cargo Transfer'), ('5', 'In Cargo Distribution'), ('6', 'Delivered'), ('7', 'Cannot delivered')], default='0', max_length=1)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShipmentCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Model ShipmentCompany Field name')),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='purchase_date',
            new_name='purchased_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='update_date',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(blank=True, default=1, editable=False, verbose_name='Model Field created_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Model Field updated_at'),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.AddField(
            model_name='package',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='order.order', verbose_name='Model Package Field order'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='order.order', verbose_name='Model LineItem Field order'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='product_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='product.productlisting', verbose_name='Model LineItem Field product_listing'),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='order.order', verbose_name='Model Fulfillment Field package'),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='shipment_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfillments', to='order.shipmentcompany', verbose_name='Model Fulfillment Field shipment_company'),
        ),
    ]
